name: Finding and customizing Github Actions
on: [push]
jobs:
  create-workflow-to-call-another-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: https://github.com/argas7/learning-github-actions@feature/customizing-actions@./.github/actions/hello-world-action.yml
