name: Finding and customizing Github Actions
on: [push]
jobs:
  create-workflow-to-call-another-one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions@feature/customizing-actions
